version: '3.3'

#networks:
#  coinform:
#    # Use a custom driver
#    driver: bridge
services:
  content_analysis:
    image: cc
#    networks:
#      - coinform
    ports:
      - "80:8000"
#    volumes:
#      - ./:/app
    command: [ "uvicorn", '--reload', '--host', '0.0.0.0', 'server:app', '--port', '8000' ]
