version: '3.7'

networks:
  coinform:
  # Use a custom driver
    driver: bridge
services:
  content_analysis:
    build:
      context: ./
      dockerfile: ./Dockerfile
      network:
        coinform
    image: content_analysis:latest
    ports:
      - "8081:8000"
    volumes:
      - "./:/app"

