version: '3.3'

networks:
  coinform:
  # Use a custom driver
    driver: bridge
services:
  content_analysis:
    build:
      dockerfile: ./Dockerfile
      context: .
    networks:
      - coinform
    ports:
      - "8081:8000"


