version: '3.3'

#networks:
#  coinform:
#    # Use a custom driver
#    driver: bridge
networks:
  coinform:
    # Use a custom driver
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1200
services:
  content_analysis:
    image: cc
    networks:
      - coinform
    ports:
      - "80:8000"
#    volumes:
#      - ./:/app
    command: [ "uvicorn", '--reload', '--host', '0.0.0.0', 'server:app', '--port', '8000' ]
